@host = localhost
@port = 3000
@apiversion = api/v1

### Recuperar Um Categoria por ID
GET http://{{host}}:{{port}}/{{apiversion}}/categorias/db3d7795-48ca-4066-86ca-6e9727cb860c


### Recuperar Todas as Categorias
GET http://{{host}}:{{port}}/{{apiversion}}/categorias

### Inserir Uma Categoria
POST http://{{host}}:{{port}}/{{apiversion}}/categorias
Content-type: application/json

{
    "nome":"Sala de Estar"
}

### Atualizar Categoria
PUT http://{{host}}:{{port}}/{{apiversion}}/categorias/db3d7795-48ca-4066-86ca-6e9727cb860b
Content-type: application/json 

{
    "id": "db3d7795-48ca-4066-86ca-6e9727cb860b",
    "nome":"Sala de Televisão"
}

### Deletar Categoria
DELETE http://{{host}}:{{port}}/{{apiversion}}/categorias/db3d7795-48ca-4066-86ca-6e9727cb860b